# Generated by Django 5.2.7 on 2025-10-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('owner', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField()),
                ('milestones', models.IntegerField()),
                ('team', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('health', models.CharField(choices=[('Good', 'Good'), ('Moderate', 'Moderate'), ('Critical', 'Critical')], max_length=20)),
                ('recent_activities', models.JSONField(default=list)),
                ('deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
    ]
